#!/bin/bash
#SBATCH --qos=debug
##SBATCH --account=desi
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --constraint=cpu

# srun --unbuffered python /global/homes/j/jjchaves/cup1d/src/cup1d/scripts/sam_like_sim.py --training_set Cabayol23 --emulator_label Cabayol23 --test_sim_label mpg_central --igm_sim_label mpg_central --drop_sim False --n_igm 0 --test
srun --unbuffered python /global/homes/j/jjchaves/cup1d/src/cup1d/scripts/sam_sim.py --emulator_label Pedersen21 --data_label mpg_central --igm_label mpg_central --cosmo_label mpg_central --n_igm 2  --cov_label Chabanier2019 --verbose --parallel --test
#mpiexec -n 32 python sam_sim.py --emulator_label Pedersen21 --data_label mpg_seed --igm_label mpg_central --cosmo_label mpg_central --n_igm 2  --cov_label Chabanier2019 --verbose --parallel


srun --nodes 1 --qos=debug --ntasks-per-node=4 --unbuffered --constraint=cpu --cpus-per-task=1 python sam_sim.py --emulator_label Pedersen21 --data_label mpg_central --igm_label mpg_central --cosmo_label mpg_central --n_igm 2  --cov_label Chabanier2019 --verbose --parallel --test