"""Generate resolved input files for the Chaves-Montero et al. 2026 analysis."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from cup1d.likelihood.input_pipeline import Args
from cup1d.utils.utils import get_path_repo


REPO_ROOT = Path(get_path_repo("cup1d"))
DEFAULT_OUTPUT = REPO_ROOT / "configs" / "cm2026" / "baseline.yaml"


def to_builtin(value: Any) -> Any:
    """Convert values used by ``Args`` into YAML-safe Python objects."""

    if isinstance(value, dict):
        return {key: to_builtin(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [to_builtin(item) for item in value]
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    return value


def make_baseline() -> dict[str, Any]:
    """Return the fully resolved CM2026 baseline configuration."""

    args = Args(pre_defined="CM2026")
    config = to_builtin(vars(args))

    # The file is already fully resolved. Reapplying this preset while loading
    # it would overwrite any subsequent hand edits.
    config["pre_defined"] = None
    return config


def write_yaml(config: dict[str, Any], output: Path, force: bool = False) -> None:
    """Write a configuration file, protecting existing files by default."""

    if output.exists() and not force:
        raise FileExistsError(
            f"{output} already exists; pass --force to overwrite it"
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/configs/generate_cm2026.py.\n"
        "# This is a fully resolved configuration and can be edited directly.\n"
    )
    output.write_text(
        header + yaml.safe_dump(config, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output YAML file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite the output file if it already exists",
    )
    return parser.parse_args()


def main() -> None:
    options = parse_args()
    write_yaml(make_baseline(), options.output, force=options.force)
    print(f"Wrote {options.output}")


if __name__ == "__main__":
    main()
