[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="cup1d"
version="2024.0.0"
authors = [
    { name="Jonas Chaves-Montero", email="jchaves@ifae.es" },
    { name="Andreu Font-Ribera", email="afont@ifae.es" },
    { name="Chris Pedersen" },
]
maintainers = [
    { name="Jonas Chaves-Montero", email="jchaves@ifae.es" },
    { name="Andreu Font-Ribera", email="afont@ifae.es" },
]
description = "Likelihood for Lyman-alpha 1D power spectrum"
readme = "README.md"
license = { text = "MIT" }
keywords = [
    "Lyman-alpha", "Cosmology", "Power Spectrum", "Emulator",
]
requires-python = ">= 3.12"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "emcee",
    "getdist",
    "astropy",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific :: Cosmology/Astrophysics",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
]

[tool.setuptools.packages.find]
include = ["cup1d","cup1d.*"]
namespaces = false

[project.urls]
Homepage="https://github.com/igmhub/cup1d"
Repository="https://github.com/igmhub/cup1d.git"
Issues="https://github.com/igmhub/cup1d/issues"
